export enum PropertyOwnersValidationStatus {
  OWNER_CONFIRMED = 'OWNER_CONFIRMED',
  MULTIPLE_OWNERS_FOUND = 'MULTIPLE_OWNERS_FOUND',
  OWNER_NOT_FOUND = 'OWNER_NOT_FOUND',
  OWNER_NOT_CONFIRMED = 'OWNER_NOT_CONFIRMED',
}
