export enum UserValidationStatus {
  PROPERTIES_FOUND = 'PROPERTIES_FOUND',
  PROPERTIES_NOT_FOUND = 'PROPERTIES_NOT_FOUND',
  ROLE_NOT_PROPERTY_OWNER = 'ROLE_NOT_PROPERTY_OWNER',
  PROPERTY_OWNER_NOT_FOUND = 'PROPERTY_OWNER_NOT_FOUND',
}
